<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>
    <PackageId>CPMCD.Dotvanta.ApiCaller</PackageId>
	  <Version>1.0.0</Version>

	  <Authors>CPMCD : Faisal Raza Khan</Authors>
	  <Description>Universal HTTP API caller for Maui, Xamarin, Windows and Web apps - GET/POST/PUT/DELETE with token/header support.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
